apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: honduras-fiduciarios-ms-blockchain
  labels:
    product: identidad
    app: requestBlockchain
    tier: backend
    phase: uat
    deployment: v1
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        product: identidad
        app: requestBlockchain
        tier: backend
        phase: uat
        deployment: v1
    spec:
      containers:
        - image: {{DOCKER_IMAGE_TAG}}
          name: honduras-fiduciarios-ms-blockchain
          imagePullPolicy: Always
          resources:
              requests:
                memory: 256Mi
              limits:
                memory: 512Mi
          env:
          - name: CONEXION_MONGO
            value: "mongodb+srv://user-honduras:Rktj11KVEzU1Xrb5@clusterhonduras-qob3j.gcp.mongodb.net"
          - name: SECRET
            value: "mysecret"
          - name: ITERATION
            value: "33"
          - name: KEY_LENGTH
            value: "256"
          - name: MS-NOTIFY
            value: http://honduras-fiduciarios-msnotify-service      
          ports: 
          - containerPort: 8081
            name: http
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
            
---
apiVersion: v1
kind: Service
metadata:
  name: honduras-fiduciarios-ms-blockchain-service
  labels:
    product: identidad
    tier: backend
    phase: uat
    deployment: v1
spec:
  selector:
    product: identidad
    app: requestBlockchain
    tier: backend
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8081
     name: http
  type: LoadBalancer
